[package]
name        = "romraider-logger"
version     = { workspace = true }
edition     = { workspace = true }
rust-version = { workspace = true }
license     = { workspace = true }
authors     = { workspace = true }
description = "Logger backend (subscriptions, datalog files, external sensors)"

[lints]
workspace = true

[dependencies]
romraider-core     = { workspace = true }
romraider-defs     = { workspace = true }
romraider-io       = { workspace = true }
romraider-protocol = { workspace = true }

thiserror  = { workspace = true }
tracing    = { workspace = true }
tokio      = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
romraider-io = { workspace = true, features = ["mock"] }
