//! SAE J2012 + Subaru-specific Diagnostic Trouble Code database.
//!
//! Извлечено из upstream RomRaider `ecu_defs.xml` (Subaru table-names
//! в формате `(P0420) ...`) — 324 Subaru-specific
//! codes — плюс key generic transmission/network (U) codes из SAE J2012
//! для machines где TCM/BCM шлют коды.
//!
//! Регенерация: см. `tools/extract_dtc_db.py`.

/// Sorted (code, description) pairs. Lookup через [`dtc_lookup`]
/// делается через `binary_search_by_key` за O(log N).
pub const DTC_DATABASE: &[(&str, &str)] = &[
    ("P0000", "Pass Code (no Dtc Detected)"),
    ("P0011", "Camshaft Pos. - Timing Over-advanced 1"),
    ("P0014", "Exhaust Avcs System 1 Range/perf"),
    ("P0016", "Crankshaft/camshaft Correlation 1A"),
    ("P0017", "Crank/cam Timing B Failure 1"),
    ("P0018", "Crankshaft/camshaft Correlation 2A"),
    ("P0019", "Crank/cam Timing B Failure 2"),
    ("P0021", "Camshaft Pos. - Timing Over-advanced 2"),
    ("P0024", "Exhaust Avcs System 2 Range/perf"),
    ("P0026", "Osv Solenoid Valve Circuit Range/perf B1"),
    ("P0028", "Osv Solenoid Valve Circuit Range/perf B2"),
    ("P0030", "Front O2 Sensor Range/perf"),
    ("P0031", "Front O2 Sensor Low Input"),
    ("P0032", "Front O2 Sensor High Input"),
    ("P0034", "Turbo Bypass Valve Circuit Low"),
    ("P0035", "Turbo Bypass Valve Circuit High"),
    ("P0037", "Rear O2 Sensor Low Input"),
    ("P0038", "Rear O2 Sensor High Input"),
    ("P0043", "Ho2s Circuit Low B1 S3"),
    ("P0044", "Ho2s Circuit High B1 S3"),
    ("P0050", "Ho2s Circuit Range/perf B2 S1"),
    ("P0051", "Ho2s Circuit Low B2 S1"),
    ("P0052", "Ho2s Circuit High B2 S1"),
    ("P0057", "Ho2s Circuit Low B2 S2"),
    ("P0058", "Ho2s Circuit High B2 S2"),
    ("P0068", "Map Sensor Range/perf"),
    ("P0076", "Intake Valve Circuit Low (bank 1)"),
    ("P0077", "Intake Valve Control High (bank 1)"),
    ("P0082", "Intake Valve Control Low (bank 2)"),
    ("P0083", "Intake Valve Control High (bank 2)"),
    ("P0101", "Maf Sensor Range/perf"),
    ("P0102", "Maf Sensor Low Input"),
    ("P0103", "Maf Sensor High Input"),
    ("P0106", "Pressure Sensor Range"),
    ("P0107", "Map Sensor Low Input"),
    ("P0108", "Map Sensor High Input"),
    ("P0111", "Iat Sensor Range/perf"),
    ("P0112", "Iat Sensor Low Input"),
    ("P0113", "Iat Sensor High Input"),
    ("P0117", "Coolant Temp Sensor Low Input"),
    ("P0118", "Coolant Temp Sensor High Input"),
    ("P0121", "Tps Range/perf"),
    ("P0122", "Tps A Low Input"),
    ("P0123", "Tps A High Input"),
    ("P0125", "Insufficient Coolant Temp (fueling)"),
    ("P0126", "Insufficient Coolant Temp (operation)"),
    ("P0128", "Thermostat Malfunction"),
    ("P0129", "Atmos. Pressure Sensor Range/perf"),
    ("P0130", "Front O2 Sensor Malfunction"),
    ("P0131", "Front O2 Sensor Low Input"),
    ("P0132", "Front O2 Sensor High Input"),
    ("P0133", "Front O2 Sensor Slow Response"),
    ("P0134", "Front O2 Sensor NO Activity"),
    ("P0136", "Rear O2 Sensor Circuit Malfunction"),
    ("P0137", "Rear O2 Sensor Low Voltage"),
    ("P0138", "Rear O2 Sensor High Voltage"),
    ("P0139", "Rear O2 Sensor Slow Response"),
    ("P0140", "Rear O2 Sensor NO Activity"),
    ("P0143", "O2 Sensor Circuit Low B1 S3"),
    ("P0144", "O2 Sensor Circuit High B1 S3"),
    ("P0145", "O2 Sensor Circuit Slow Response B1 S3"),
    ("P0151", "O2 Sensor Circuit Low B2 S1"),
    ("P0152", "O2 Sensor Circuit High B2 S1"),
    ("P0153", "O2 Sensor Circuit Slow Response B2 S1"),
    ("P0154", "O2 Sensor Circuit Open B2 S1"),
    ("P0157", "O2 Sensor Circuit Low B2 S2"),
    ("P0158", "O2 Sensor Circuit High B2 S2"),
    ("P0159", "O2 Sensor Circuit Slow Response B2 S2"),
    ("P0160", "O2 Sensor NO Activity B2 S2"),
    ("P0171", "System Too Lean"),
    ("P0172", "System Too Rich"),
    ("P0174", "System Too Lean B2"),
    ("P0175", "System Too Rich B2"),
    ("P0181", "Fuel Temp Sensor A Range/perf"),
    ("P0182", "Fuel Temp Sensor A Low Input"),
    ("P0183", "Fuel Temp Sensor A High Input"),
    ("P0196", "Oil Temp Sensor Range/perf"),
    ("P0197", "Oil Temp Sensor Low"),
    ("P0198", "Oil Temp Sensor High"),
    ("P0222", "Tps B Low Input"),
    ("P0223", "Tps B High Input"),
    ("P0230", "Fuel Pump Primary Circuit"),
    ("P0244", "Wastegate Solenoid A Range/perf"),
    ("P0245", "Wastegate Solenoid A Low"),
    ("P0246", "Wastegate Solenoid A High"),
    ("P0249", "Wastegate Solenoid B Low"),
    ("P0250", "Wastegate Solenoid B High"),
    ("P0261", "Fuel Injector #1 Circuit Low"),
    ("P0264", "Fuel Injector #2 Circuit Low"),
    ("P0267", "Fuel Injector #3 Circuit Low"),
    ("P0270", "Fuel Injector #4 Circuit Low"),
    ("P0301", "Misfire Cylinder 1"),
    ("P0302", "Misfire Cylinder 2"),
    ("P0303", "Misfire Cylinder 3"),
    ("P0304", "Misfire Cylinder 4"),
    ("P0305", "Misfire Cylinder 5"),
    ("P0306", "Misfire Cylinder 6"),
    ("P0327", "Knock Sensor 1 Low Input"),
    ("P0328", "Knock Sensor 1 High Input"),
    ("P0332", "Knock Sensor 2 Low Input"),
    ("P0333", "Knock Sensor 2 High Input"),
    ("P0335", "Crankshaft Pos. Sensor A Malfunction"),
    ("P0336", "Crankshaft Pos. Sensor A Range/perf"),
    ("P0340", "Camshaft Pos. Sensor A Malfunction"),
    ("P0341", "Camshaft Pos. Sensor A Range/perf"),
    ("P0345", "Camshaft Pos. Sensor A Bank 2"),
    ("P0350", "Ignition Coil Primary/secondary"),
    ("P0365", "Camshaft Pos. Sensor B Bank 1"),
    ("P0390", "Camshaft Pos. Sensor B Bank 2"),
    ("P0400", "Egr Flow"),
    ("P0410", "Secondary Air Pump System"),
    ("P0411", "Secondary Air Pump Incorrect Flow"),
    ("P0413", "Secondary Air Pump A Open"),
    ("P0414", "Secondary Air Pump A Shorted"),
    ("P0416", "Secondary Air Pump B Open"),
    ("P0417", "Secondary Air Pump B Shorted"),
    ("P0418", "Secondary Air Pump Relay A"),
    ("P0420", "Cat Efficiency Below Threshold"),
    ("P0441", "Evap Incorrect Purge Flow"),
    ("P0442", "Evap Leak Detected (small)"),
    ("P0444", "Evap Purge Valve Circuit Low"),
    ("P0445", "Evap Purge Valve Circuit High"),
    ("P0447", "Evap Vent Control Circuit Open"),
    ("P0448", "Evap Vent Control Circuit Shorted"),
    ("P0451", "Evap Pressure Sensor Range/perf"),
    ("P0452", "Evap Pressure Sensor Low Input"),
    ("P0453", "Evap Pressure Sensor High Input"),
    ("P0456", "Evap Leak Detected (very Small)"),
    ("P0457", "Evap Leak Detected (fuel Cap)"),
    ("P0458", "Evap Purge Valve Circuit Low"),
    ("P0459", "Evap Purge Valve Circuit High"),
    ("P0461", "Fuel Level Sensor Range/perf"),
    ("P0462", "Fuel Level Sensor Low Input"),
    ("P0463", "Fuel Level Sensor High Input"),
    ("P0464", "Fuel Level Sensor Intermittent"),
    ("P0480", "Radiator Fan Relay 1 Low"),
    ("P0483", "Radiator Fan Rationality Check"),
    ("P0500", "Vehicle Speed Sensor A"),
    ("P0502", "Vehicle Speed Sensor Low Input"),
    ("P0503", "Vehicle Speed Sensor Intermittent"),
    ("P0506", "Idle Control Rpm Lower Than Expected"),
    ("P0507", "Idle Control Rpm High Than Expected"),
    ("P0508", "Idle Control Circuit Low"),
    ("P0509", "Idle Control Circuit High"),
    ("P0512", "Starter Request Circuit"),
    ("P0519", "Idle Control Malfunction (fail-safe)"),
    ("P0545", "Egt Sensor Circuit Low"),
    ("P0546", "Egt Sensor Circuit High"),
    ("P0558", "Alternator Circuit Low"),
    ("P0559", "Alternator Circuit High"),
    ("P0562", "System Voltage Low"),
    ("P0563", "System Voltage High"),
    ("P0565", "Cruise Control Set Signal"),
    ("P0600", "Serial Communication Link"),
    ("P0602", "Control Module Prog. Error"),
    ("P0604", "Control Module Ram Error"),
    ("P0605", "Control Module Rom Error"),
    ("P0607", "Control Module Performance"),
    ("P0638", "Throttle Actuator Range/perf"),
    ("P0691", "Radiator Fan Circuit Low"),
    ("P0692", "Radiator Fan Circuit High"),
    ("P0700", "Transmission Control System"),
    ("P0701", "Transmission Control System Range/performance"),
    ("P0702", "Transmission Control System Electrical"),
    ("P0703", "Brake Switch Input Malfunction"),
    ("P0704", "Clutch Switch Input Circuit Malfunction"),
    ("P0705", "Transmission Range Sensor Malfunction"),
    (
        "P0706",
        "Transmission Range Sensor Circuit Range/performance",
    ),
    ("P0710", "Atf Temp Sensor Malfunction"),
    ("P0715", "Torque Converter Turbine Speed Malfunction"),
    ("P0716", "Torque Converter Turbine Speed Range/perf"),
    ("P0720", "AT Vehicle Speed Sensor High"),
    ("P0725", "Engine Speed Input Malfunction"),
    ("P0726", "Engine Speed Input Range/perf"),
    ("P0730", "Incorrect Gear Ratio"),
    ("P0731", "Gear 1 Incorrect Ratio"),
    ("P0732", "Gear 2 Incorrect Ratio"),
    ("P0733", "Gear 3 Incorrect Ratio"),
    ("P0734", "Gear 4 Incorrect Ratio"),
    ("P0740", "Torque Converter Clutch Circuit Malfunction"),
    ("P0741", "Torque Converter Clutch Malfunction"),
    ("P0743", "Torque Converter Clutch Lock-up Duty Solenoid"),
    ("P0748", "Pressure Control Line Pressure Duty Solenoid"),
    ("P0750", "Shift Solenoid A Malfunction"),
    ("P0753", "Shift Solenoid A Electrical"),
    ("P0755", "Shift Solenoid B Malfunction"),
    ("P0758", "Shift Solenoid B Electrical"),
    ("P0760", "Shift Solenoid C Malfunction"),
    ("P0771", "AT Low Clutch Timing Solenoid Malfunction"),
    ("P0778", "AT 2-4 Brake Pressure Solenoid Malfunction"),
    ("P0785", "AT 2-4 Brake Timing Solenoid Malfunction"),
    ("P0851", "Neutral Switch Input Low"),
    ("P0852", "Neutral Switch Input High"),
    ("P0864", "Tcm Communication Range/perf"),
    ("P0865", "Tcm Communication Circuit Low"),
    ("P0866", "Tcm Communication Circuit High"),
    ("P1026", "Vvl Systems 1 Performance"),
    ("P1028", "Vvl Systems 2 Performance"),
    ("P1086", "Tgv Pos. 2 Circuit Low"),
    ("P1087", "Tgv Pos. 2 Circuit High"),
    ("P1088", "Tgv Pos. 1 Circuit Low"),
    ("P1089", "Tgv Pos. 1 Circuit High"),
    ("P1090", "Tgv System 1 (valve Open)"),
    ("P1091", "Tgv System 1 (valve Close)"),
    ("P1092", "Tgv System 2 (valve Open)"),
    ("P1093", "Tgv System 2 (valve Close)"),
    ("P1094", "Tgv Signal 1 (open)"),
    ("P1095", "Tgv Signal 1 (short)"),
    ("P1096", "Tgv Signal 2 (open)"),
    ("P1097", "Tgv Signal 2 (short)"),
    ("P1110", "Atmos. Pressure Sensor Low Input"),
    ("P1111", "Atmos. Pressure Sensor High Input"),
    ("P1112", "Atmos. Pressure Sensor Range/perf"),
    ("P1130", "Front O2 Sensor Malfunction (open)"),
    ("P1131", "Front O2 Sensor Malfunction (short)"),
    ("P1134", "Front O2 Sensor Microcomputer"),
    ("P1139", "Front O2 Sensor Range/perf"),
    ("P1141", "Maf Sensor High Input"),
    ("P1142", "Maf Sensor Low Input"),
    ("P1146", "Map Sensor Range/perf"),
    ("P1152", "Front O2 Sensor Range/perf Low B1 S1"),
    ("P1153", "Front O2 Sensor Range/perf High B1 S1"),
    ("P1154", "O2 Sensor Range/perf Low B2 S1"),
    ("P1155", "O2 Sensor Range/perf High B2 S1"),
    ("P1160", "Abnormal Return Spring"),
    ("P1199", "Differential Pressure Sensor"),
    ("P1230", "Fuel Pump Control Unit Malfunction"),
    ("P1235", "Icv Solenoid Circuit Low"),
    ("P1236", "Icv Solenoid Circuit High"),
    ("P1237", "Ecv Solenoid Low Pos. Pressure"),
    ("P1238", "Ecv Solenoid High Pos. Pressure"),
    ("P1239", "Ecv Solenoid Low Neg. Pressure"),
    ("P1240", "Ecv Solenoid High Neg. Pressure"),
    ("P1241", "2 Stage Twin Turbo System (single)"),
    ("P1242", "2 Stage Twin Turbo System (twin)"),
    ("P1244", "Wastegate Solenoid Malfunction (low)"),
    ("P1245", "Wastegate Solenoid Malfunction (fail-safe)"),
    ("P1247", "Relief Valve Solenoid 1 Circuit Low"),
    ("P1248", "Relief Valve Solenoid 1 Circuit High"),
    ("P1249", "Relief Valve Solenoid 2 Circuit Low"),
    ("P1250", "Relief Valve Solenoid 2 Circuit High"),
    ("P1282", "Pcv System Circuit (open)"),
    ("P1301", "Misfire (high Temp Exhaust Gas)"),
    ("P1306", "Ocv Solenoid Signal 1 Malfunction (open)"),
    ("P1307", "Ocv Solenoid Signal 1 Malfunction (short)"),
    ("P1308", "Ocv Solenoid Signal 2 Malfunction (open)"),
    ("P1309", "Ocv Solenoid Signal 2 Malfunction (short)"),
    ("P1312", "Egt Sensor Malfunction"),
    ("P1400", "Fuel Tank Pressure Sol. Low"),
    ("P1410", "Secondary Air Pump Valve Stuck Open"),
    ("P1418", "Secondary Air Pump Circuit Shorted"),
    ("P1420", "Fuel Tank Pressure Sol. High Input"),
    ("P1443", "Vent Control Solenoid Function Problem"),
    ("P1446", "Fuel Tank Sensor Control Circuit Low"),
    ("P1447", "Fuel Tank Sensor Control Circuit High"),
    ("P1448", "Fuel Tank Sensor Control Range/perf"),
    ("P1480", "Radiator Fan Relay 1 Circuit High"),
    ("P1491", "Pcv (blowby) Function Problem"),
    ("P1492", "Egr Solenoid Signal 1 Malfunction (low)"),
    ("P1493", "Egr Solenoid Signal 1 Malfunction (high)"),
    ("P1494", "Egr Solenoid Signal 2 Malfunction (low)"),
    ("P1495", "Egr Solenoid Signal 2 Malfunction (high)"),
    ("P1496", "Egr Signal 3 Circuit Low"),
    ("P1497", "Egr Solenoid Signal 3 Malfunction (high)"),
    ("P1498", "Egr Signal 4 Circuit Low"),
    ("P1499", "Egr Signal 4 Circuit High"),
    ("P1507", "Idle Control Malfunction (fail-safe)"),
    ("P1518", "Starter Switch Low Input"),
    ("P1519", "Imrc Stuck Closed"),
    ("P1520", "Imrc Circuit Malfunction"),
    ("P1544", "Egt Too High"),
    ("P1560", "Back-up Voltage Malfunction"),
    ("P1590", "Neutral Pos. Switch High Input (at)"),
    ("P1591", "Neutral Pos. Switch Low Input (at)"),
    ("P1594", "AT Diagnosis Signal Malfunction"),
    ("P1595", "AT Diagnosis Signal Low Input"),
    ("P1596", "AT Diagnosis Signal High Input"),
    ("P1602", "Control Module Programming Error"),
    ("P1616", "Sbds Interactive Codes"),
    ("P1700", "Tps Circuit Malfunction (at)"),
    ("P1701", "Cruise Control Set Signal Malfunction (at)"),
    ("P1703", "Low Clutch Timing Solenoid Malfunction (at)"),
    ("P1711", "Engine Torque Signal #1 Malfunction"),
    ("P1712", "Engine Torque Signal #2 Malfunction"),
    ("P2004", "Tgv - Intake Manifold Runner 1 Stuck Open"),
    ("P2005", "Tgv - Intake Manifold Runner 2 Stuck Open"),
    ("P2006", "Tgv - Intake Manifold Runner 1 Stuck Closed"),
    ("P2007", "Tgv - Intake Manifold Runner 2 Stuck Closed"),
    ("P2008", "Tgv - Intake Manifold Runner 1 Circuit Open"),
    ("P2009", "Tgv - Intake Manifold Runner 1 Circuit Low"),
    ("P2011", "Tgv - Intake Manifold Runner 2 Circuit Open"),
    ("P2012", "Tgv - Intake Manifold Runner 2 Circuit Low"),
    ("P2016", "Tgv - Intake Manifold Runner 1 Pos. Sensor Low"),
    ("P2017", "Tgv - Intake Manifold Runner 1 Pos. Sensor High"),
    ("P2021", "Tgv - Intake Manifold Runner 2 Pos. Sensor Low"),
    ("P2022", "Tgv - Intake Manifold Runner 2 Pos. Sensor High"),
    ("P2088", "Ocv Solenoid A1 Circuit Open"),
    ("P2089", "Ocv Solenoid A1 Circuit Short"),
    ("P2090", "Ocv Solenoid B1 Circuit Open"),
    ("P2091", "Ocv Solenoid B1 Circuit Short"),
    ("P2092", "Ocv Solenoid A2 Circuit Open"),
    ("P2093", "Ocv Solenoid A2 Circuit Short"),
    ("P2094", "Ocv Solenoid B2 Circuit Open"),
    ("P2095", "Ocv Solenoid B2 Circuit Short"),
    ("P2096", "Post Catalyst Too Lean B1"),
    ("P2097", "Post Catalyst Too Rich B1"),
    ("P2098", "Post Catalyst Too Lean B2"),
    ("P2099", "Post Catalyst Too Rich B2"),
    ("P2101", "Throttle Actuator Circuit Range/perf"),
    ("P2102", "Throttle Actuator Circuit Low"),
    ("P2103", "Throttle Actuator Circuit High"),
    ("P2109", "Tps A Minimum Stop Perf"),
    ("P2122", "Tps D Circuit Low Input"),
    ("P2123", "Tps D Circuit High Input"),
    ("P2127", "Tps E Circuit Low Input"),
    ("P2128", "Tps E Circuit High Input"),
    ("P2135", "Tps A/b Voltage"),
    ("P2138", "Tps D/e Voltage"),
    ("P2227", "Baro. Pressure Circuit Range/perf"),
    ("P2228", "Baro. Pressure Circuit Low Input"),
    ("P2229", "Baro. Pressure Circuit High Input"),
    ("P2419", "Evap Switching Valve Low"),
    ("P2420", "Evap Switching Valve High"),
    ("P2431", "Secondary Air Pump Circuit Range/perf"),
    ("P2432", "Secondary Air Pump Circuit Low"),
    ("P2433", "Secondary Air Pump Circuit High"),
    ("P2440", "Secondary Air Pump Valve 1 Stuck Open"),
    ("P2441", "Secondary Air Pump Valve 1 Stuck Closed"),
    ("P2442", "Secondary Air Pump Valve 2 Stuck Open"),
    ("P2443", "Secondary Air Pump 2 Stuck Closed"),
    ("P2444", "Secondary Air Pump 1 Stuck ON B1"),
    ("P2503", "Charging System Voltage Low"),
    ("P2504", "Charging System Voltage High"),
    ("U0073", "Control Module Communication Bus Off"),
    ("U0101", "Lost Communication With Tcm"),
    ("U0121", "Lost Communication With Anti-lock Brake System"),
    ("U0140", "Lost Communication With Body Control Module"),
    ("U0155", "Lost Communication With Instrument Panel Cluster"),
];

/// Найти описание DTC-кода (`P0301`, `C1234`, etc). Возвращает `None`
/// если код не известен — caller отображает просто номер.
#[must_use]
pub fn dtc_lookup(code: &str) -> Option<&'static str> {
    DTC_DATABASE
        .binary_search_by_key(&code, |(c, _)| c)
        .ok()
        .map(|i| DTC_DATABASE[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn database_is_sorted() {
        for w in DTC_DATABASE.windows(2) {
            assert!(
                w[0].0 < w[1].0,
                "DTC_DATABASE must be sorted: {} >= {}",
                w[0].0,
                w[1].0
            );
        }
    }

    #[test]
    fn lookup_known_codes() {
        assert!(dtc_lookup("P0030").is_some());
        assert!(dtc_lookup("P0700").is_some());
        assert!(dtc_lookup("P0420").is_some());
    }

    #[test]
    fn lookup_unknown_returns_none() {
        assert_eq!(dtc_lookup("P9999"), None);
        assert_eq!(dtc_lookup("XXXXX"), None);
    }

    #[test]
    fn database_size_is_reasonable() {
        // Sanity: a few hundred entries expected (Subaru + generic).
        assert!(
            DTC_DATABASE.len() >= 100,
            "DTC_DATABASE too small: {}",
            DTC_DATABASE.len()
        );
    }
}
